theme: jekyll-theme-minimal

#aangevuld 10 juni 2022
logo: https://www.spineo.org/wp-content/uploads/2020/09/cropped-spineo_logo-removed-3.png
title: [The title of your site]
description: [A short description of your site's purpose]
